### ISSUE TITLE
Field named model inside model fails to generate code

### ISSUE THREAD

**Issue by blombergniklas** [AhmedElywa/create-nexus-type#7]
Thanks for a sweet lib. Make stuff easy to work with.

Found an issue with a field name `model` inside of a model.
Just checked the source fast and I think I saw the issue. Leaving this here for now and dropping a PR if I manage to sort it out later on.

Example not working:
```
model Car {
  id              Int         @id
  model_year      Int         @default(0)
  license_plate   String       @default("")
  brand           Brand
  model           Model 
}
```
This works:
```
model Car {
  id              Int         @id
  model_year      Int         @default(0)
  license_plate   String       @default("")
  brand           Brand
  car_model           Model
}
```

**Comment by AhmedElywa** [comment]
Thanks @blombergniklas for catch this error i fixed it and pushed in` v1.1.6 ` please update your version thanks .
