### ISSUE TITLE
Support Nexus framework

### ISSUE THREAD

**Issue by yantakus** [AhmedElywa/create-nexus-type#9]
From v0.20 nexus has breaking changes. Are there any plans to support it?

**Comment by AhmedElywa** [comment]
Today i update my tool to support new package name `@nexus/schema`  for support new framework i will work in new one

**Comment by AhmedElywa** [comment]
@yantakus  just update my tool to work by default with new version of `nexus` framework 
to use `@nexus/schema` you need to add `-s` flag
